services:
  scraper:
    build: .
    container_name: scraper_tool
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    env_file:
      - .env
    # Supprimer restart: unless-stopped pour éviter la boucle
    command: python src/main.py