version: '3.8'

services:
  scraper:
    build: .
    container_name: scraper_tool
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    command: python src/main.py